[package]
name = "typstyle"
version = "0.11.1"
edition = "2021"
authors = ["Wenzhuo Liu"]
license-file = "LICENSE"
description = "A typst source code formatter"
repository = "https://github.com/Enter-tainer/typstyle"
homepage = "https://enter-tainer.github.io/typstyle/"

include = [
  "src/**/*.rs",
  "/LICENSE",
  "/README.md",
  "build.rs",
  "tests/assets.rs",
]

[[bin]]
name = "typstyle"
path = "src/main.rs"

[lib]
name = "typstyle_core"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]


[dependencies]
clap = { version = "4.5.2", features = ["derive", "env"] }
itertools = "0.12.1"
once_cell = "1.19.0"
pretty = "0.12.3"
wasm-bindgen = "0.2"
typst-syntax = "0.11.0"

[dev-dependencies]
insta = { version = "1.36.1" }
libtest-mimic = "0.7.0"
pathdiff = "0.2.1"
pretty_assertions = "1.4.0"
typst-ts-core = { version = "0.4.2-rc9", default-features = false, features = [
  "no-content-hint",
] }
typst-ts-compiler = { version = "0.4.2-rc9", default-features = false, features = [
  "no-content-hint",
  "system-compile",
] }
typst-assets = { version = "0.11.0", features = ["fonts"] }
typst-svg = "0.11.0"

[build-dependencies]
anyhow = "1.0.80"
vergen = { version = "8.3.1", features = [
  "build",
  "cargo",
  "git",
  "git2",
  "rustc",
] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[[test]]
name = "assets"
harness = false

[profile.release]
debug = true
