[package]
name = "typstyle"
version = "0.11.34"
edition = "2021"
authors = ["Wenzhuo Liu"]
license-file = "LICENSE"
description = "Beautiful and reliable typst code formatter"
repository = "https://github.com/Enter-tainer/typstyle"
homepage = "https://enter-tainer.github.io/typstyle/"

include = [
  "src/**/*.rs",
  "/LICENSE",
  "/README.md",
  "build.rs",
  "tests/assets.rs",
  "tests/repo-e2e.rs",
]

[[bin]]
name = "typstyle"
path = "src/main.rs"
required-features = ["cli"]
test = false
doctest = false
bench = false
doc = false

[lib]
name = "typstyle_core"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]


[dependencies]
itertools = "0.13.0"
pretty = "0.12.3"
typst-syntax = { git = "https://github.com/Myriad-Dreamin/typst.git", tag = "tinymist-v0.11.23" }

anyhow = "1"
once_cell = { version = "1.19.0", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
clap = { version = "4.5.4", features = ["derive", "env"], optional = true }
walkdir = { version = "2", optional = true }
clap_complete = { version = "4.5.26", optional = true }

[dev-dependencies]
insta = { version = "1.39.0" }
libtest-mimic = "0.7.3"
pathdiff = "0.2.1"
pretty_assertions = "1.4.0"
walkdir = "2"
reflexo = { git = "https://github.com/Myriad-Dreamin/typst.ts", branch = "tinymist-v0.11.23", default-features = false, features = [
] }
reflexo-typst = { git = "https://github.com/Myriad-Dreamin/typst.ts", branch = "tinymist-v0.11.23", default-features = false, features = [
  "no-content-hint",
  "system-compile",
] }
typst-assets = { git = "https://github.com/typst/typst-assets", rev = "4ee794cf8fb98eb67194e757c9820ab8562d853b", features = [
  "fonts",
] }
typst-render = { git = "https://github.com/Myriad-Dreamin/typst.git", tag = "tinymist-v0.11.23" }
typst-pdf = { git = "https://github.com/Myriad-Dreamin/typst.git", tag = "tinymist-v0.11.23" }
typst = { git = "https://github.com/Myriad-Dreamin/typst.git", tag = "tinymist-v0.11.23" }

[build-dependencies]
anyhow = "1"
vergen = { version = "8.3.1", features = ["build", "cargo", "rustc"] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[[test]]
name = "assets"
harness = false

[[test]]
name = "repo-e2e"
harness = false

[features]

default = ["cli", "wasm", "git-info", "completion"]
cli = ["clap", "once_cell", "walkdir"]
wasm = ["wasm-bindgen"]
git-info = ["vergen/git", "vergen/git2"]
completion = ["cli", "dep:clap_complete"]

[profile.test]
opt-level = 3

[profile.ci]
inherits = "release"
debug = true
