[package]
name = "typst-geshihua"
version = "0.11.0-rc1-0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "typst-geshihua"
path = "src/main.rs"

[lib]
name = "typst_geshihua"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]


[dependencies]
clap = { version = "4.5.2", features = ["derive", "env"] }
itertools = "0.12.1"
once_cell = "1.19.0"
pretty = "0.12.3"
wasm-bindgen = "0.2"
typst-syntax = { git = "https://github.com/typst/typst.git", tag = "v0.11.0-rc1" }

[dev-dependencies]
insta = { version = "1.36.1", features = ["yaml"] }
libtest-mimic = "0.7.0"
pathdiff = "0.2.1"
pretty_assertions = "1.4.0"

[build-dependencies]
anyhow = "1.0.80"
vergen = { version = "8.3.1", features = [
  "build",
  "cargo",
  "git",
  "git2",
  "rustc",
] }

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[[test]]
name = "assets"
harness = false

[profile.release]
debug = true
